// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const missingSupabaseEnv = [
  !import.meta.env.VITE_SUPABASE_URL ? 'VITE_SUPABASE_URL' : null,
  !import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ? 'VITE_SUPABASE_PUBLISHABLE_KEY' : null,
].filter((name): name is string => Boolean(name));

export const supabaseConfigError = missingSupabaseEnv.length > 0
  ? `Configuração do Supabase ausente: ${missingSupabaseEnv.join(', ')}.`
  : null;

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://missing-supabase-url.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'missing-supabase-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
